"""new fields in user model

Revision ID: 287b097fa427
Revises: 513e1cfcc67c
Create Date: 2020-07-16 12:14:32.112874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287b097fa427'
down_revision = '513e1cfcc67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
